### ISSUE TITLE
Suggestie om repository te hernoemen naar ImaerAutoCalc

### ISSUE THREAD

**Issue by Hilbrand** [ProvincieZeeland/ImaerAutoCalc#1]
De repository naam, afgezien van de (bewuste?) typo in de naam (A en E omgedraaid), is dezelfde als een een eigen repository van AERIUS: https://github.com/AERIUS/IMAER. Die repository wordt gebruikt om het model te publiceren, en ook wordt gebruikt om te synchroniseren met geonovum. Dus om verwarring te voorkomen is het misschien beter om deze repository te hernoemen. Wellicht is de naam van de plugin `ImaerAutoCalc` dan een betere naam.

**Comment by rvanmaaren** [comment]
Beste [Hilbrand](https://github.com/Hilbrand), Uw suggestie is doorgevoerd. Dank voor de oplettendheid.
